apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend-deploy
  name: backend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-deploy
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/labproj20/uiconfronter-docker
        name: uiconfronter
        ports:
        - containerPort: 8080
        resources: {}
        envFrom:
        - secretRef: 
            name: uiconfronter-secret  
        - configMapRef: 
            name: uiconfronter-configmap
status: {}
