apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend-deploy
  name: frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-deploy
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/labproj20/ng-uiconfronter-docker:1.0
        name: ng-uiconfronter-docker
        ports:
        - containerPort: 80
        resources: {}
        envFrom: 
        - configMapRef: 
            name: ng-uiconfronter-configmap 
status: {}
